apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-servicemonitor
  namespace: monitoring
  labels:
    release: kps  
spec:
  selector:
    matchLabels:
      app: api            
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http         
      path: /metrics
      interval: 30s

