apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: demo
  labels:
    app: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: api
  ports:
    - name: http        
      port: 5000
      targetPort: 5000



